### ISSUE TITLE
Customizable "AUTO GENERATED FILE" message

### ISSUE THREAD

**Issue by lukasschwab** [andrewring/github-distributed-owners#44]
Great tool, dead easy to install/use 😁 

Enhancement request: I'd like to be able to insert some project-specific messaging into the "Do Not Manually Update" preamble/postamble of the generated CODEOWNERS file. Currently, that message is hardcoded:

```
################################################################################
#                             AUTO GENERATED FILE
#                            Do Not Manually Update
#                              For details, see:
#        https://github.com/andrewring/github-distributed-owners#readme
################################################################################
```

Ideally I'd like to point other engineers to the _build target_ they should use to regenerate the file (`make codeowners`), or to some external documentation for how we use `OWNERS` (e.g. some `go/codeowners` URL).

A `-m, --message` flag would do the trick; for example:

```shell
$ github-distributed-owners --message 'Run "make codeowners" to regenerate'
################################################################################
#                             AUTO GENERATED FILE
#                            Do Not Manually Update
#                    Run "make codeowners" to regenerate
#                              For details, see:
#        https://github.com/andrewring/github-distributed-owners#readme
################################################################################
```

**Comment by andrewring** [comment]
This is now available in [release v0.1.9](https://github.com/andrewring/github-distributed-owners/releases/tag/v0.1.9). :)
